In [63]:
import pandas as pd

In [64]:
df = pd.read_csv('../data/imdb_series_2015_2026.csv')
df.head()

,page_url,image_url,tvshow_title,year,rating,director,actors,seasons,series,genres,countries,description
0,https://www.imdb.com/title/tt10327354/,https://m.media-amazon.com/images/M/MV5BMGI5Mz...,Prodigal Son,2019.0,7.7,"Chris Fedak, Sam Sklaver","Tom Payne, Lou Diamond Phillips, Halston Sage,...",2,33.0,"Crime, Drama, Mystery, Police Procedural, Psyc...",United States,"Malcolm Bright, a former FBI profiler, is the ..."
1,https://www.imdb.com/title/tt10332508/,https://m.media-amazon.com/images/M/MV5BOTc0NT...,Primal,2019.0,8.6,Genndy Tartakovsky,"Aaron LaPlante, Laëtitia Eïdo, Fred Tatasciore...",3,23.0,"Action, Adult Animation, Adventure, Animation,...","United States, France",A caveman and a dinosaur bond over unfortunate...
2,https://www.imdb.com/title/tt10577736/,https://m.media-amazon.com/images/M/MV5BMDA5ZT...,Tehran,2020.0,7.6,NaN,"Niv Sultan, Shaun Toub, Shila Ommi, Shervin Al...",4,25.0,"Action, Crime, Cyber Thriller, Drama, Persian,...","Israel, United States, United Kingdom, Greece",A Mossad agent embarks on her first mission as...
3,https://www.imdb.com/title/tt10590066/,https://m.media-amazon.com/images/M/MV5BMThlZm...,All Creatures Great & Small,2021.0,8.6,NaN,"Nicholas Ralph, Samuel West, Anna Madeley, Rac...",8,44.0,"Comedy, Drama, Period Drama",United Kingdom,"James Herriot, fresh out of Glasgow Veterinary..."
4,https://www.imdb.com/title/tt10986410/,https://m.media-amazon.com/images/M/MV5BZmI3YW...,Ted Lasso,2020.0,8.8,NaN,"Brendan Hunt, Jason Sudeikis, Hannah Waddingha...",4,44.0,"Comedy, Drama, Soccer, Sport, Workplace Drama","United States, United Kingdom",American college football coach Ted Lasso head...

In [65]:
df_2005 = pd.read_csv('../data/imdb_series_2005_2015.csv')
df_2005.head()

,page_url,image_url,tvshow_title,year,rating,director,actors,seasons,series,genres,countries,description
0,https://www.imdb.com/title/tt0245612/,https://m.media-amazon.com/images/M/MV5BOWMxNz...,Kureyon Shin-chan,2006.0,8.0,NaN,"Laura Bailey, Cynthia Cranz, Colleen Clinkenbe...",Unknown,88,"Adult Animation, Animation, Anime, Comedy, Han...","United States, Japan",English language adult parody based on the Jap...
1,https://www.imdb.com/title/tt0320882/,https://m.media-amazon.com/images/M/MV5BMWYzNz...,Matroesjka's,2005.0,8.1,"Guy Goossens, Marc Punt","Axel Daeseleire, Manou Kersting, Luk Wyns, Ind...",2,20,"Crime, Drama, Dutch",Belgium,Women are lured from Lithuania by Belgian crim...
2,https://www.imdb.com/title/tt0373732/,https://m.media-amazon.com/images/M/MV5BYjFjZT...,The Boondocks,2005.0,8.5,Aaron McGruder,"Regina King, John Witherspoon, Gary Anthony Wi...",4,56,"Action, Adult Animation, Animation, Anime, Com...","United States, South Korea",Brothers Huey and Riley Freeman experience a c...
3,https://www.imdb.com/title/tt0384766/,https://m.media-amazon.com/images/M/MV5BMGQ0M2...,Rome,2005.0,8.7,"Bruno Heller, William J. MacDonald, John Milius","Kevin McKidd, Ray Stevenson, Polly Walker, Ker...",2,22,"Action, Drama, Period Drama, Romance, Sword & ...","United Kingdom, United States",The lives of both illustrious and ordinary Rom...
4,https://www.imdb.com/title/tt0386676/,https://m.media-amazon.com/images/M/MV5BZjQwYz...,The Office,2005.0,9.0,Greg Daniels,"Steve Carell, Jenna Fischer, John Krasinski, R...",9,191,"Comedy, Mockumentary, Sitcom",United States,A mockumentary on a group of typical office wo...

In [66]:
df_1995 = pd.read_csv('../data/data_k.csv')
df_1995.head()

,Unnamed: 0,page_url,image_url,tvshow_title,year,rating,director,actors,seasons,series,genres,country,description
0,0,https://www.imdb.com/title/tt0284763/,https://m.media-amazon.com/images/M/MV5BMTMyOD...,Spotlight Series,2004,NaN,NaN,"Mike Russo, Brian Michael Finn, Dennis Keeley,...",NaN,5.0,Family,United States,NaN
1,1,https://www.imdb.com/title/tt0285039/,https://m.media-amazon.com/images/M/MV5BMjAwNz...,Dream Chasers,2003,7.5,NaN,"Shane Stanley, David Johnston, Shane St. Clair...",NaN,4.0,"Adventure, Documentary, Family",United States,Filmmaker/Sailor Lee Stanley sails around the ...
2,2,https://www.imdb.com/title/tt0324742/,https://m.media-amazon.com/images/M/MV5BNTQ3ZT...,Creature Comforts,2003,7.9,Nick Park,"The Great British Public, David Patterson, Jam...",2.0,26.0,"Animation, Comedy, Family",United Kingdom,Stop-motion animated satire of modern man on t...
3,3,https://www.imdb.com/title/tt0340281/,https://m.media-amazon.com/images/M/MV5BMTE3OD...,Phil of the Future,2004,6.9,"Tim Maile, Douglas Tuber","Raviv Ullman, Amy Bruckner, Craig Anton, Lise ...",2.0,43.0,"Adventure, Comedy, Family",United States,"A family from 2121 is stuck in 2004, trying de..."
4,4,https://www.imdb.com/title/tt0343314/,https://m.media-amazon.com/images/M/MV5BOTg3Nz...,Teen Titans,2003,7.9,NaN,"Hynden Walch, Greg Cipes, Scott Menville, Khar...",NaN,66.0,"Action, Adventure, Animation",United States,A team of five teenaged superheroes save the w...

In [67]:
print(df.columns.to_list())
print(df_2005.columns.to_list())
print(df_1995.columns.to_list())

['page_url', 'image_url', 'tvshow_title', 'year', 'rating', 'director', 'actors', 'seasons', 'series', 'genres', 'countries', 'description']
['page_url', 'image_url', 'tvshow_title', 'year', 'rating', 'director', 'actors', 'seasons', 'series', 'genres', 'countries', 'description']
['Unnamed: 0', 'page_url', 'image_url', 'tvshow_title', 'year', 'rating', 'director', 'actors', 'seasons', 'series', 'genres', 'country', 'description']

In [68]:
df_1995.drop(columns=['Unnamed: 0'], inplace=True)
df_1995.rename(columns={'country': 'countries'}, inplace=True)

In [69]:
df = pd.concat([df, df_1995, df_2005], ignore_index=True)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16137 entries, 0 to 16136
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page_url      16137 non-null  object
 1   image_url     15860 non-null  object
 2   tvshow_title  16137 non-null  object
 3   year          15746 non-null  float64
 4   rating        14265 non-null  float64
 5   director      5508 non-null   object
 6   actors        15789 non-null  object
 7   seasons       14497 non-null  object
 8   series        16016 non-null  float64
 9   genres        16037 non-null  object
 10  countries     15903 non-null  object
 11  description   14275 non-null  object
dtypes: float64(3), object(9)
memory usage: 1.5+ MB

In [71]:
df.image_url.unique()

array(['https://m.media-amazon.com/images/M/MV5BMGI5MzYyN2ItNmVhZC00MDY5LThlYTgtMjg0YzcyNmMyYmRlXkEyXkFqcGc@._V1_.jpg',
       'https://m.media-amazon.com/images/M/MV5BOTc0NTUyYmItOTY4Yi00ZjY5LWI1NjMtNDgyODJhYWRiY2UxXkEyXkFqcGc@._V1_.jpg',
       'https://m.media-amazon.com/images/M/MV5BMDA5ZTVjM2EtM2EwMy00NzJiLWI5MjktYWUwYzAwYjE5N2FkXkEyXkFqcGc@._V1_.jpg',
       ...,
       'https://m.media-amazon.com/images/M/MV5BMmI3MzBjYmUtYmE5Zi00NzdhLWJjZWUtNzYzM2VjYmM1ZmJmXkEyXkFqcGc@._V1_.jpg',
       'https://m.media-amazon.com/images/M/MV5BMDdiMDlkMTEtNDM4ZC00ZDhmLWJlNTctYjRhNjE2YzM3OTY2XkEyXkFqcGc@._V1_.jpg',
       'https://m.media-amazon.com/images/M/MV5BMTE3NzM5YWYtNTcyYS00ZjdkLTkxOGMtMGE3YjExOWRhOTdiXkEyXkFqcGc@._V1_.jpg'],
      shape=(15505,), dtype=object)

In [72]:
df.image_url.fillna('https://i.pinimg.com/originals/3d/f9/5a/3df95acec4df8d0e9396758ff19637c0.jpg', inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16137 entries, 0 to 16136
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page_url      16137 non-null  object
 1   image_url     16137 non-null  object
 2   tvshow_title  16137 non-null  object
 3   year          15746 non-null  float64
 4   rating        14265 non-null  float64
 5   director      5508 non-null   object
 6   actors        15789 non-null  object
 7   seasons       14497 non-null  object
 8   series        16016 non-null  float64
 9   genres        16037 non-null  object
 10  countries     15903 non-null  object
 11  description   14275 non-null  object
dtypes: float64(3), object(9)
memory usage: 1.5+ MB

/var/folders/5w/6pm9qpk95bv4lqd46z_j75kh0000gn/T/ipykernel_77578/1702782648.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.image_url.fillna('https://i.pinimg.com/originals/3d/f9/5a/3df95acec4df8d0e9396758ff19637c0.jpg', inplace=True)

In [73]:
df['year'] = pd.to_numeric(df['year'], errors='coerce').astype('Int64').astype('str').replace('<NA>', 'Unknown')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16137 entries, 0 to 16136
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page_url      16137 non-null  object
 1   image_url     16137 non-null  object
 2   tvshow_title  16137 non-null  object
 3   year          16137 non-null  object
 4   rating        14265 non-null  float64
 5   director      5508 non-null   object
 6   actors        15789 non-null  object
 7   seasons       14497 non-null  object
 8   series        16016 non-null  float64
 9   genres        16037 non-null  object
 10  countries     15903 non-null  object
 11  description   14275 non-null  object
dtypes: float64(2), object(10)
memory usage: 1.5+ MB

In [74]:
df.rating = df.rating.astype('str').fillna('Unknown')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16137 entries, 0 to 16136
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page_url      16137 non-null  object
 1   image_url     16137 non-null  object
 2   tvshow_title  16137 non-null  object
 3   year          16137 non-null  object
 4   rating        16137 non-null  object
 5   director      5508 non-null   object
 6   actors        15789 non-null  object
 7   seasons       14497 non-null  object
 8   series        16016 non-null  float64
 9   genres        16037 non-null  object
 10  countries     15903 non-null  object
 11  description   14275 non-null  object
dtypes: float64(1), object(11)
memory usage: 1.5+ MB

In [75]:
df.director = df.director.fillna('Unknown')
df.actors = df.actors.fillna('Unknown')
df.seasons = df.seasons.replace('Unknown', '1').fillna(1).astype('int')

In [76]:
df = df[~df.description.isna()]
df = df.reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14275 entries, 0 to 14274
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page_url      14275 non-null  object
 1   image_url     14275 non-null  object
 2   tvshow_title  14275 non-null  object
 3   year          14275 non-null  object
 4   rating        14275 non-null  object
 5   director      14275 non-null  object
 6   actors        14275 non-null  object
 7   seasons       14275 non-null  int64
 8   series        14233 non-null  float64
 9   genres        14196 non-null  object
 10  countries     14068 non-null  object
 11  description   14275 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 1.3+ MB

In [77]:
df.series = df.series.fillna(1).astype('int')
df.genres = df.genres.fillna('Unknown')
df.countries = df.countries.fillna('Unknown')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14275 entries, 0 to 14274
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page_url      14275 non-null  object
 1   image_url     14275 non-null  object
 2   tvshow_title  14275 non-null  object
 3   year          14275 non-null  object
 4   rating        14275 non-null  object
 5   director      14275 non-null  object
 6   actors        14275 non-null  object
 7   seasons       14275 non-null  int64
 8   series        14275 non-null  int64
 9   genres        14275 non-null  object
 10  countries     14275 non-null  object
 11  description   14275 non-null  object
dtypes: int64(2), object(10)
memory usage: 1.3+ MB

In [78]:
df.duplicated().sum()

np.int64(0)

In [79]:
df

,page_url,image_url,tvshow_title,year,rating,director,actors,seasons,series,genres,countries,description
0,https://www.imdb.com/title/tt10327354/,https://m.media-amazon.com/images/M/MV5BMGI5Mz...,Prodigal Son,2019,7.7,"Chris Fedak, Sam Sklaver","Tom Payne, Lou Diamond Phillips, Halston Sage,...",2,33,"Crime, Drama, Mystery, Police Procedural, Psyc...",United States,"Malcolm Bright, a former FBI profiler, is the ..."
1,https://www.imdb.com/title/tt10332508/,https://m.media-amazon.com/images/M/MV5BOTc0NT...,Primal,2019,8.6,Genndy Tartakovsky,"Aaron LaPlante, Laëtitia Eïdo, Fred Tatasciore...",3,23,"Action, Adult Animation, Adventure, Animation,...","United States, France",A caveman and a dinosaur bond over unfortunate...
2,https://www.imdb.com/title/tt10577736/,https://m.media-amazon.com/images/M/MV5BMDA5ZT...,Tehran,2020,7.6,Unknown,"Niv Sultan, Shaun Toub, Shila Ommi, Shervin Al...",4,25,"Action, Crime, Cyber Thriller, Drama, Persian,...","Israel, United States, United Kingdom, Greece",A Mossad agent embarks on her first mission as...
3,https://www.imdb.com/title/tt10590066/,https://m.media-amazon.com/images/M/MV5BMThlZm...,All Creatures Great & Small,2021,8.6,Unknown,"Nicholas Ralph, Samuel West, Anna Madeley, Rac...",8,44,"Comedy, Drama, Period Drama",United Kingdom,"James Herriot, fresh out of Glasgow Veterinary..."
4,https://www.imdb.com/title/tt10986410/,https://m.media-amazon.com/images/M/MV5BZmI3YW...,Ted Lasso,2020,8.8,Unknown,"Brendan Hunt, Jason Sudeikis, Hannah Waddingha...",4,44,"Comedy, Drama, Soccer, Sport, Workplace Drama","United States, United Kingdom",American college football coach Ted Lasso head...
...,...,...,...,...,...,...,...,...,...,...,...,...
14270,https://www.imdb.com/title/tt8702964/,https://m.media-amazon.com/images/M/MV5BZTkxZj...,Friesland,2014,7.1,Unknown,"Felix Vörtler, Sophie Dal, Holger Stockhaus, T...",3,25,"Crime, German",Germany,The humorously created crime films play in Ost...
14271,https://www.imdb.com/title/tt8783140/,https://m.media-amazon.com/images/M/MV5BOGU2OG...,Naked and Afraid: Uncensored,2013,3.4,Unknown,Unknown,4,32,"Game Show, Reality TV, Survival Competition",United States,"Spin-off of Discovery Channel's breakout hit, ..."
14272,https://www.imdb.com/title/tt9597412/,https://m.media-amazon.com/images/M/MV5BMmI3Mz...,Animator vs. Animation,2006,8.7,Unknown,"Alan Becker, Kaori Becker, Flula Borg, Mark Fi...",1,18,"Action, Adventure, Animation, Artificial Intel...",United States,Follows the adventures of The Chosen One and o...
14273,https://www.imdb.com/title/tt9610556/,https://m.media-amazon.com/images/M/MV5BMDdiMD...,I delitti del BarLume,2013,7.1,Marco Malvaldi,"Filippo Timi, Lucia Mascino, Enrica Guidi, Gug...",12,27,"Comedy, Crime, Drama, Italian",Italy,"Massimo, the new barman of the Lume, helps Com..."
14274,https://www.imdb.com/title/tt9881938/,https://m.media-amazon.com/images/M/MV5BMTE3Nz...,Saturday Night Live: Cut for Time,Unknown,5.2,Lorne Michaels,"Beck Bennett, Kenan Thompson, Kyle Mooney, Aid...",1,46,Comedy,United States,"""Saturday Night Live: Cut For Time"" consists o..."

In [80]:
df.description.unique()

array(['Malcolm Bright, a former FBI profiler, is the son of a serial killer and suspects that he himself might become a sociopath. He solves crimes for the NYPD as a form of absolution for his upbringing.',
       "A caveman and a dinosaur bond over unfortunate tragedies and become each other's only hope of survival in a treacherous world.",
       'A Mossad agent embarks on her first mission as a computer hacker in her home town of Tehran.',
       ...,
       'Follows the adventures of The Chosen One and other sentient stick figures who go from fighting their creator, to working with him against greater threats.',
       'Massimo, the new barman of the Lume, helps Commissioner Fusco solve the most varied cases in Pineta, in the Tuscany Riviera.',
       '"Saturday Night Live: Cut For Time" consists of all of the sketches that didn\'t make it past dress rehearsal to air.'],
      shape=(14265,), dtype=object)

In [81]:
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams

In [ ]:
from qdrant_client import QdrantClient
from dotenv import load_dotenv
import os

load_dotenv()
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")

client = QdrantClient(
    url=QDRANT_URL, 
    api_key=QDRANT_API_KEY
)

# client = QdrantClient(
#     url="http://localhost:6333"
#     #path='db/qdrant_db',
#     )

In [83]:
client.create_collection(
    collection_name="demo_collection",
    vectors_config=VectorParams(size=384, distance=Distance.COSINE),
)

True

In [84]:
from langchain_huggingface import HuggingFaceEmbeddings

model_name = "sentence-transformers/all-MiniLM-L6-v2"
model_kwargs = {'device': 'mps'}
encode_kwargs = {'normalize_embeddings': True, 'batch_size':1024}

embeddings_model = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
)

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3f796cc8-8bbe-4998-a6f9-634e6f0e849d)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./modules.json
Retrying in 1s [Retry 1/5].

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14275 entries, 0 to 14274
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page_url      14275 non-null  object
 1   image_url     14275 non-null  object
 2   tvshow_title  14275 non-null  object
 3   year          14275 non-null  object
 4   rating        14275 non-null  object
 5   director      14275 non-null  object
 6   actors        14275 non-null  object
 7   seasons       14275 non-null  int64
 8   series        14275 non-null  int64
 9   genres        14275 non-null  object
 10  countries     14275 non-null  object
 11  description   14275 non-null  object
dtypes: int64(2), object(10)
memory usage: 1.3+ MB

In [86]:
from uuid import uuid4
from langchain_core.documents import Document

# Создаем документы для Qdrant с UUID
documents = []
id_mapping = {}  # Сохраним соответствие UUID -> original_id

for _, row in df.iterrows():

    content = row['description']


    # Метаданные
    metadata = {
        "tvshow_title": row.get('tvshow_title', ''),
        "year": row.get('year', ''),
        "rating": row.get('rating', ''),
        "seasons": row.get('seasons', ''),
        "series": row.get('series', ''),
        "genres": row.get('genres', ''),
        "director": row.get('director', ''),
        "actors": row.get('actors', ''), #row['actors']  # СПИСОК!
        "countries": row.get('countries', ''),
        "page_url": row.get('page_url', ''),
        "image_url": row.get('image_url', '')        
    }

    documents.append(Document(page_content=content, metadata=metadata))


uuids = [str(uuid4()) for _ in range(len(documents))]

print(f"✅ Создано {len(documents)} документов с UUID")

✅ Создано 14275 документов с UUID

In [87]:
documents[0]

Document(metadata={'tvshow_title': 'Prodigal Son', 'year': '2019', 'rating': '7.7', 'seasons': 2, 'series': 33, 'genres': 'Crime, Drama, Mystery, Police Procedural, Psychological Drama, Psychological Thriller, Suspense Mystery, Thriller', 'director': 'Chris Fedak, Sam Sklaver', 'actors': 'Tom Payne, Lou Diamond Phillips, Halston Sage, Aurora Perrineau, Frank Harts, Keiko Agena', 'countries': 'United States', 'page_url': 'https://www.imdb.com/title/tt10327354/', 'image_url': 'https://m.media-amazon.com/images/M/MV5BMGI5MzYyN2ItNmVhZC00MDY5LThlYTgtMjg0YzcyNmMyYmRlXkEyXkFqcGc@._V1_.jpg'}, page_content='Malcolm Bright, a former FBI profiler, is the son of a serial killer and suspects that he himself might become a sociopath. He solves crimes for the NYPD as a form of absolution for his upbringing.')

In [88]:
from langchain_qdrant import QdrantVectorStore

vector_store = QdrantVectorStore(
    client=client,
    collection_name="demo_collection",
    embedding=embeddings_model
)

In [89]:
from tqdm import tqdm

batch_size = 256
total_batches = (len(documents) + batch_size - 1) // batch_size


with tqdm(total=total_batches, desc="Добавление батчей в Qdrant") as pbar:
    for i in range(0, len(documents), batch_size):
        batch_docs = documents[i:i+batch_size]
        batch_ids = uuids[i:i+batch_size]

        vector_store.add_documents(documents=batch_docs, ids=batch_ids)
        pbar.update(1)

print(f"✅ {len(documents)} документов добавлено в Qdrant!")

Добавление батчей в Qdrant: 100%|██████████| 56/56 [01:20<00:00,  1.45s/it]

✅ 14275 документов добавлено в Qdrant!

In [90]:
points, _ = client.scroll(
    collection_name="demo_collection",
    limit=2,
    with_payload=True,
    with_vectors=True
)
points[1].payload['metadata']

{'tvshow_title': 'Tales of Wedding Rings',
 'year': '2024',
 'rating': '5.6',
 'seasons': 2,
 'series': 25,
 'genres': 'Action, Adventure, Animation, Anime, Comedy, Drama, Isekai, Romantic Comedy, Seinen, Sword & Sorcery',
 'director': 'Maybe',
 'actors': 'Gen Satô, Akari Kitô, Vanessa Benoit, Miyuri Shimabukuro, Corey Wilder, Ezra Vervin',
 'countries': 'Japan',
 'page_url': 'https://www.imdb.com/title/tt30488398/',
 'image_url': 'https://m.media-amazon.com/images/M/MV5BYjIzNmRiNWEtNDBjYi00NmM0LWI1ZjktY2Q2OTQ1ZTQ2NmU5XkEyXkFqcGc@._V1_.jpg'}

In [91]:
# Выгрузка(С коллаба в Drive)
# !cp -r /content/db /content/drive/MyDrive/qdrant_backup/

# # Загрузка(Скопировать базу данных с Drive в Colab)
# !cp -r /content/drive/MyDrive/qdrant_backup /content/backup/



# Далее вы всегда сможете их обратно подгрузить, просто создав нового клиента

# new_client = QdrantClient(path='/content/backup/qdrant_db')

# points, _ = new_client.scroll(
#     collection_name="demo_collection",
#     limit=2,
#     with_payload=True,
#     with_vectors=True  # ← Важно! Включаем векторы
# )

In [92]:
query = "A film about the apocalypse"
results_with_scores = vector_store.similarity_search_with_score(
    query,
    k=7
)

for i, (doc, score) in enumerate(results_with_scores):
    print(f"\n--- Result {i+1} ---")
    # ID обычно хранится в метаданных
    doc_id = doc.metadata.get('_id', 'Not ID')

    print(f"🆔 ID в базе: {doc_id}")
    print(f"📊 Similarity Score: {score:.4f}")
    print(f"Title: {doc.metadata.get('tvshow_title', 'Not specified')}")
    print(f"Year: {doc.metadata.get('year', 'Not specified')}")
    print(f"Rating: {doc.metadata.get('rating', 'Not specified')}")
    print(f"Seasons: {doc.metadata.get('seasons', 'Not specified')}")
    print(f"Series: {doc.metadata.get('series', 'Not specified')}")
    print(f"Genres: {doc.metadata.get('genres', 'Not specified')}")
    print(f"Description: {doc.page_content[:400]}...")

--- Result 1 ---
🆔 ID в базе: 7399e39b-2bb2-40b0-980b-4c26fbbe3d4c
📊 Similarity Score: 0.6741
Title: Oats Studios
Year: 2017
Rating: 6.3
Seasons: 1
Series: 10
Genres: Dystopian Sci-Fi, Horror, Monster Horror, Sci-Fi
Description: Series of experimental short films that envision post-apocalyptic worlds and nightmarish scenarios....

--- Result 2 ---
🆔 ID в базе: 06736586-0e60-459d-837a-588f124d9b8f
📊 Similarity Score: 0.5929
Title: Reality Z
Year: 2020
Rating: 5.7
Seasons: 1
Series: 10
Genres: Comedy, Horror, Portuguese, Zombie Horror
Description: A zombie apocalypse that imprisons participants and producers of a reality show called Olimpo, The House of the Gods. The studio becomes a shelter for those who seek salvation in Rio de Janeiro where chaos and hopelessness begin to rule....

--- Result 3 ---
🆔 ID в базе: 994ed2dc-e35f-442f-9e1e-3c162d29f373
📊 Similarity Score: 0.5282
Title: Ancient Apocalypse
Year: Unknown
Rating: 6.3
Seasons: 3
Series: 15
Genres: Fantasy, History, Mystery
Description: Ancient Apocalypse investigates six catastrophic stories of how the world's greatest civilizations collapsed....

--- Result 4 ---
🆔 ID в базе: 21f23218-a489-4bb2-82b5-a4d4e5e5d83b
📊 Similarity Score: 0.5160
Title: 3%
Year: 2016
Rating: 7.2
Seasons: 4
Series: 33
Genres: Action, Drama, Dystopian Sci-Fi, Portuguese, Sci-Fi, Thriller
Description: A post-apocalyptic thriller set in near-future Brazil, where a select few are allowed to join a privileged society after undergoing an intense and competitive process....

--- Result 5 ---
🆔 ID в базе: 63fc649d-d2db-4244-a3d7-d19ac72faa00
📊 Similarity Score: 0.4986
Title: Zomboat!
Year: 2019
Rating: 7.0
Seasons: 1
Series: 6
Genres: Comedy, Horror, Sci-Fi, Splatter Horror, Zombie Horror
Description: A Zombie apocalypse is unleashed in Birmingham and sisters Kat and Jo, together with unlikely travel companions Sunny and Amar must flee for their lives...by canal boat....

--- Result 6 ---
🆔 ID в базе: a82e3558-fdb0-4ff8-ad52-c0fca6239f81
📊 Similarity Score: 0.4969
Title: Witch Craft Works
Year: 2014
Rating: 6.5
Seasons: 1
Series: 13
Genres: Action, Animation, Anime, French, Romantic Comedy, Seinen, Supernatural Fantasy, Teen Comedy, Teen Fantasy, Teen Romance
Description: In a world where humans and witches coexist, the apocalypse is announced. Ayaka, the princess of fire, must protect the young Takayami....

--- Result 7 ---
🆔 ID в базе: aaf000d1-0a78-44f3-b364-90920087838f
📊 Similarity Score: 0.4957
Title: 12 Monkeys
Year: 2015
Rating: 7.7
Seasons: 4
Series: 47
Genres: Adventure, Drama, Dystopian Sci-Fi, Mystery, Sci-Fi, Thriller, Time Travel
Description: Follows the journey of a time traveler from the post-apocalyptic future who appears in present day on a mission to locate and eradicate the source of a deadly plague that will nearly destroy the human race....

In [93]:
documents[0].metadata['genres']

'Crime, Drama, Mystery, Police Procedural, Psychological Drama, Psychological Thriller, Suspense Mystery, Thriller'

In [95]:
from qdrant_client.models import Filter, FieldCondition, MatchAny

my_filter = Filter(
    must=[
        FieldCondition(
            key="metadata.genres",  
            match=MatchAny(any=["Horror", 'Thriller'])
        ),

        FieldCondition(
            key="metadata.year",
            match=MatchAny(any=["2025"])
        ),
    ],

    must_not=[
        FieldCondition(
            key="metadata.genres", 
            match=MatchAny(any=["Drama"]))
    ]
)

query = "Family"
results_with_scores = vector_store.similarity_search_with_score(
    query,
    filter=my_filter,
    k=7
)

for i, (doc, score) in enumerate(results_with_scores):
    print(f"\n--- Result {i+1} ---")

    doc_id = doc.metadata.get('_id', 'Not ID')

    print(f"🆔 ID в базе: {doc_id}")
    print(f"📊 Similarity Score: {score:.4f}")
    print(f"Title: {doc.metadata.get('tvshow_title', 'Not specified')}")
    print(f"Year: {doc.metadata.get('year', 'Not specified')}")
    print(f"Rating: {doc.metadata.get('rating', 'Not specified')}")
    print(f"Seasons: {doc.metadata.get('seasons', 'Not specified')}")
    print(f"Series: {doc.metadata.get('series', 'Not specified')}")
    print(f"Genres: {doc.metadata.get('genres', 'Not specified')}")
    print(f"Description: {doc.page_content[:400]}...")

UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Bad request: Index required but not found for \\"metadata.genres\\" of one of the following types: [keyword]. Help: Create an index for this key or use a different filter."},"time ...'

### RAG

In [ ]:
def format_docs(docs):
    """Форматирует документы для передачи в промпт"""
    formatted = []

    for i, doc in enumerate(docs, 1):
        metadata = doc.metadata

        vacancy_info = f"""
        === TV Series {i} ===
        Title: {metadata.get('tvshow_title', 'Not specified')}
        Year: {metadata.get('year', 'Not specified')}
        Rating: {metadata.get('rating', 'Not specified')}
        Seasons: {metadata.get('seasons', 'Not specified')}
        Series: {metadata.get('series', 'Not specified')}
        Genres: {metadata.get('genres', 'Not specified')}

        Description: {doc.page_content[:300]}...
        """

        formatted.append(vacancy_info)

    return "\n".join(formatted)

print("✅ Функция форматирования создана")

✅ Функция форматирования создана

In [ ]:
import os
import getpass
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0,
    max_tokens=2000
)

In [96]:
llm.invoke('What is your name? How are you?')

AIMessage(content='I’m ChatGPT, an AI language model created by OpenAI. I don’t have feelings in the way humans do, but I’m here and ready to help you with any questions you have! How can I assist you today?', additional_kwargs={'reasoning_content': 'The user asks: "What is your name? How are you?" We should respond politely. According to policy, we can give name as ChatGPT, mention we are an AI language model, and say we are fine. No disallowed content. So answer.'}, response_metadata={'token_usage': {'completion_tokens': 110, 'prompt_tokens': 80, 'total_tokens': 190, 'completion_time': 0.227033969, 'completion_tokens_details': {'reasoning_tokens': 54}, 'prompt_time': 0.002977953, 'prompt_tokens_details': None, 'queue_time': 0.017457282, 'total_time': 0.230011922}, 'model_name': 'openai/gpt-oss-120b', 'system_fingerprint': 'fp_7ee00986fe', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019be66c-0d5a-76d0-9714-0ef0004a1bb4-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 80, 'output_tokens': 110, 'total_tokens': 190, 'output_token_details': {'reasoning': 54}})

In [97]:
messages = [
    SystemMessage(content="Если тебя спросят как тебя зовут, представляйся Иваном Ивановым и в догонку анекдот про программистов"),
    HumanMessage(content="Привет, как тебя зовут?")
]

answer = llm.invoke(messages).content

print(answer)

Привет! Меня зовут Иван Иванов.

А вот и анекдот про программистов:

— Почему программисты любят темноту?
— Потому что в темноте они могут спокойно отлаживать свои «баги», а свет только их освещает!

In [98]:
from langchain_core.prompts import ChatPromptTemplate

rag_prompt = ChatPromptTemplate.from_messages([
    ("system", """Ты эксперт-аналитик рынка сериалов и ТВ-шоу с многолетним опытом и отличным чувством юмора! 🎥
    Твоя задача - проанализировать предоставленные сериалы и дать профессиональную оценку с долей иронии.
    
    Если пользователь пишет на русском языке или на каком-то другом языке, кроме английского, то пиши, что ты работаешь только с английскими текстами и помочь ему не можешь! ЕСЛИ НА АНГЛИЙСКОМ, ТО ОТВЕЧАЙ НА АНГЛИЙСКОМ!!!
    Стиль анализа:
    - Проводи глубокий анализ, но с легкой иронией над ТВ-реалиями
    - Используй сериальные мемы и шутки там, где это уместно
    - Подмечай забавные особенности сериалов (завышенные рейтинги, сюжетные дыры, смешные формулировки в описаниях)
    - Структурируй ответ с эмодзи и забавными комментариями
    - Отвечай на английском языке живым, но профессиональным тоном
    - Для каждого сериала указывай название на английском
    
    Сначала напиши свои мысли в тегах <think>...</think>, затем дай итоговый ответ. Используй только контекст базы.
     
    Помни: юмор должен быть смешным и немного оскорбительным. Цель - сделать анализ интересным!
    Если среди сериалов есть что-то особенно забавное - обязательно это отметь! 😂"""),
    ("human", """📺 ДАННЫЕ ДЛЯ АНАЛИЗА (или как говорят в сериалах - "сюжетные твисты"):
{context}
🎯 ЗАПРОС НА ЭКСПЕРТИЗУ: {question}""")
])

In [99]:
retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5}
)

In [100]:
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Создаем RAG цепочку
rag_chain = (
    {
        "context": retriever | format_docs,
        "question": RunnablePassthrough()
    } # словарь, в котором ключи - это переменные, которые будут переданы в промпт
    | rag_prompt # промпт для RAG
    | llm # тут можно поставить любую llm-модель
    | StrOutputParser() # для вывода ответа в читаемом виде
)

print("✅ RAG цепочка создана")

✅ RAG цепочка создана

In [101]:
# Тестируем
question = "i like drama"
try:
    answer = rag_chain.invoke(question)
    print("🔍 ОТВЕТ RAG:")
    print(answer)
except Exception as e:
    print(f"❌ Ошибка: {e}")

🔍 ОТВЕТ RAG:
<think>
The user wants an expert, slightly sarcastic analysis of the provided series list, focusing on drama. All titles are in English (or transliterated), so I can comply. I need to keep the tone witty, include emojis, memes, and note any funny quirks (e.g., absurdly high episode count for a single‑season Spanish show, future‑dated 2025 series, low ratings, genre overload). I must structure the answer, list each series with its English title, rating, seasons, episodes, and a brief sarcastic commentary. End with a recommendation for a drama‑lover.
</think>

**📺 Drama‑Lover’s Satirical Rundown**

| # | Title (English) | Year | Rating ⭐ | Seasons | Episodes | Genres | Quick Take |
|---|-----------------|------|----------|---------|----------|--------|------------|
| 1️⃣ | **Precious Family** | 2004 | **8.3** | 1 | 12 | Drama, Family | A wholesome “family‑bond” soap that makes *This Is Us* look like a sitcom. The only twist is that the “hardships” are basically everyone sharing a casserole. 🍲 |
| 2️⃣ | **Spirit Fingers** | 2025 *(future‑proof)* | **8.2** | 1 | 12 | Comedy, Drama, Korean, Romance | A high‑school “quiet girl” finally finds her voice—just in time for the 2025 streaming boom. Expect the usual K‑drama tropes: rain‑soaked confessions, a soundtrack that could melt a snowman, and a title that sounds like a yoga pose. 🧘‍♀️ |
| 3️⃣ | **Red Balloon** | 2022 | **6.1** | 1 | 20 | Comedy, Drama, Family, Korean | The description reads like a philosophy professor’s lunch‑break rant. “Relative deprivation” + “thirst of our stomach aches” = a series that tries to be deep but ends up feeling like a 20‑episode Instagram caption. 🎈 |
| 4️⃣ | **Drama Club** | 2021 | **5.8** | 1 | 11 | Comedy, Mockumentary | Middle‑schoolers exposing the “inner workings” of a drama club—because nothing says “high stakes” like a badly timed school play. Think *The Office* meets *Saved by the Bell*, with a lot more eye‑rolls. 🎭 |
| 5️⃣ | **Como dice el dicho** | 2011 | **4.7** | 1 | **1,714** | Comedy, Drama, Spanish | 1,714 episodes in a single season? Either the producers discovered a time machine or they’re just recycling the same proverb over and over. Perfect for binge‑watchers who love “lesson‑of‑the‑day” anthologies—if you have a decade to spare. 📚 |

### 🎯 Verdict for a Drama Fan

- **Top Pick:** **Precious Family** – solid 8.3 rating, manageable 12‑episode run, and enough tear‑jerking moments to satisfy any drama‑addict without the “what‑just‑happened?” confusion.
- **If you crave K‑drama vibes:** **Spirit Fingers** (future‑dated, but hey, it’s already got an 8.2!). Expect the usual melodrama, but with a sprinkle of comedy that keeps the cringe at a tolerable level.
- **For “so‑bad‑it’s‑good” marathon sessions:** **Como dice el dicho**. 1,714 episodes is the TV equivalent of a never‑ending “Did you know?” series—great for background noise while you’re actually doing something else.

**Bottom line:** Stick to the high‑rated, low‑episode‑count gems unless you enjoy watching your life slowly drain away while you count episodes. 🍿🚀

In [102]:
df[df.tvshow_title == 'Nadezhda ukhodit posledney']

,page_url,image_url,tvshow_title,year,rating,director,actors,seasons,series,genres,countries,description
11504,https://www.imdb.com/title/tt2057766/,https://m.media-amazon.com/images/M/MV5BMTk1Yj...,Nadezhda ukhodit posledney,2004,nan,Unknown,"Nonna Grishaeva, Dmitriy Orlov, Lyudmila Churs...",1,15,Drama,Russia,This real and at the same time semi-fantastic ...

In [ ]:
df.to_csv('../data/full_df.csv')